### ISSUE TITLE
`npm test` won't work

### ISSUE THREAD

**Issue by RudthMael** [americansystems/serverless-es6-jest#2]
When I try running `npm test` from the installed serverless service, it says:

```
npm test

> serverless-es6-jest@0.1.0 test /Users/mael/Development/serverless-spider-house/serverless-es6-jest
> jest

 FAIL  tests/helloSvc.spec.js
  ● Test suite failed to run

    SyntaxError: Unexpected reserved word

      at transformAndBuildScript (node_modules/jest/node_modules/jest-cli/node_modules/jest-runtime/build/transform.js:284:10)
      at process._tickCallback (node.js:364:9)
```

**Comment by RudthMael** [comment]
nvm, you need `babel-jest` for node 4.
node 6+ runs just fine :)

**Comment by mikepugh** [comment]
Ah ok, thanks for the info
